In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

path = '/content/LIVER_DATA (1)csv.txt'
df = pd.read_csv(path, sep='\t', low_memory=False, header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,406,407,408,409,410,411,412,413,414,415
0,.,0,.,F,B,0,62.0000,160.0000,24.2187,NaN,...,1994,.,.,Y,Y,09362,19282,22537,22537,09362
1,.,1,.,F,A,0,53.0000,163.0000,19.9481,NaN,...,1994,.,.,Y,Y,02666,01054,14353,14353,02666
2,.,0,.,F,O,0,54.0000,165.0000,19.8347,NaN,...,1994,.,.,N,Y,Unknown,Unknown,02821,02821,11129
3,.,0,.,M,B,0,89.0000,180.0000,27.4691,NaN,...,1994,.,.,Y,Y,03503,23002,23002,23002,03503
4,.,0,.,F,O,0,57.0000,163.0000,21.4536,NaN,...,1994,.,.,N,Y,Unknown,Unknown,01054,01054,06107

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/LIVER_DATA.DAT"

df = pd.read_csv(file_path,
                 sep="\t",
                 dtype=str,
                 low_memory=False,
                 header=None)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,406,407,408,409,410,411,412,413,414,415
0,.,0,.,F,B,0,62.0000,160.0000,24.2187,NaN,...,1994,.,.,Y,Y,09362,19282,22537,22537,09362
1,.,1,.,F,A,0,53.0000,163.0000,19.9481,NaN,...,1994,.,.,Y,Y,02666,01054,14353,14353,02666
2,.,0,.,F,O,0,54.0000,165.0000,19.8347,NaN,...,1994,.,.,N,Y,Unknown,Unknown,02821,02821,11129
3,.,0,.,M,B,0,89.0000,180.0000,27.4691,NaN,...,1994,.,.,Y,Y,03503,23002,23002,23002,03503
4,.,0,.,F,O,0,57.0000,163.0000,21.4536,NaN,...,1994,.,.,N,Y,Unknown,Unknown,01054,01054,06107

In [ ]:
with open(file_path, 'r') as f:
    for line in f:
            # Process each line, e.g., split by space or comma
      data = line.strip().split() # or line.strip().split(',')
print(data)

['.', '0', '0', 'F', 'O', '1', '69.8000', '157.5000', '28.1381', '4', 'N', '0', '0', '2080', '1', '4213', '.', '1', 'N', 'N', '6220', '69.8000', '157.5000', '.', '.', '.', '.', '.', '4', '6220', '49', '.', '04/04/2025', '03/31/2025', 'N', '.', '4', '288244', '28.1', '28.1', '.', 'Y', '3', 'FL', '1', '.', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '1887347', '0', 'Y', 'N', 'N', 'N', '01APR2025:10:34:29.000', '.', 'Y', '.', '.', '.', '.', '.', '.', '.', '3.6', '1', '0.3', 'N', '1', '1.05', 'MELD', '20', '3.45', '144', '.', '3.6', '1', '0.3', 'N', '1', '1.05', 'MELD', '20', '3.45', '144', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '2025', '.', '.', 'N', 'Y', 'Unknown', 'Unknown', '20429', '20429', '11253']

In [ ]:
len(data)

234

In [ ]:
official_header_list = [
"ABO","ABO_DON","ABO_MAT","ACADEMIC_LEVEL_TCR","ACADEMIC_LEVEL_TRR",
"ACADEMIC_PRG_TCR","ACADEMIC_PRG_TRR","ACUTE_REJ_EPI","ADMISSION_DATE","ADMIT_DATE_DON",
"AGE","AGE_DON","AGE_GROUP","ALBUMIN_TX","ALCOHOL_HEAVY_DON","AMIS","ANTIHYPE_DON",
"ARGININE_DON","ARTIFICIAL_LI_TCR","ARTIFICIAL_LI_TRR","ASCITES_TCR","ASCITES_TRR_OLD",
"ASCITES_TX","BACT_PERIT_TCR","BILIARY","BLOOD_INF_CONF_DON","BLOOD_INF_DON","BMI_CALC",
"BMI_DON_CALC","BMI_TCR","BMIS","BUN_DON","BW4","BW6","C1","C2","CANCER_FREE_INT_DON",
"CANCER_SITE_DON","CARDARREST_NEURO","CDC_RISK_HIV_DON","CITIZEN_COUNTRY","CITIZENSHIP",
"CITIZENSHIP_DON","CLIN_INFECT_DON","CLSTR_OLD","CLSTRTYP_OLD","CMV_DON","CMV_IGG",
"CMV_IGG_DON","CMV_IGM","CMV_IGM_DON","CMV_NUCLEIC_DON","CMV_OLD_LIV_DON","CMV_STATUS",
"CMV_TEST_DON","COD","COD_CAD_DON","COD_WL","COD2","COD3","COLD_ISCH","COMPOSITE_DEATH_DATE",
"CONTIN_ALCOHOL_OLD_DON","CONTIN_CIG_DON","CONTIN_COCAINE_DON","CONTIN_IV_DRUG_OLD_DON",
"CONTIN_OTH_DRUG_DON","CONTROLLED_DON","CORE_COOL_DON","CORONARY_ANGIO_DON",
"CORONARY_ANGIO_NORM_DON","CREAT_DON","CREAT_TX","CTR_CODE","DA1","DA2","DATA_TRANSPLANT",
"DATA_WAITLIST","DAYSWAIT_CHRON","DB1","DB2","DDAVP_DON","DDR1","DDR2","DEATH_CIRCUM_DON",
"DEATH_DATE","DEATH_MECH_DON","DGN_TCR","DGN2_TCR","DIAB","DIABDUR_DON","DIABETES_DON",
"DIAG","DIAL_TX","DIET_DON","DIFFUSE_CHOLANG","DIS_ALKPHOS","DIS_SGOT","DISCHARGE_DATE",
"DISTANCE","DIURETICS_DON","DOBUT_DON_OLD","DON_TY","DONATION_DON","DONOR_ID",
"DOPAMINE_DON_OLD","DQ1","DQ2","DR51","DR51_2","DR52","DR52_2","DR53","DR53_2","DRMIS",
"EBV_IGG_CAD_DON","EBV_IGM_CAD_DON","EBV_SEROSTATUS","EBV_TEST_DON","ECD_DONOR","ECMO",
"EDUCATION","EDUCATION_DON","ENCEPH_TCR","ENCEPH_TRR_OLD","ENCEPH_TX","END_BMI_CALC",
"END_DATE","END_OPO_CTR_CODE","END_STAT","ETHCAT","ETHCAT_DON","ETHNICITY","EVER_APPROVED",
"EXC_AT_TX","EXC_CASE","EXC_CURRENT","EXC_DIAG_ID","EXC_EVER","EXC_EVER_APPROVED_ANY",
"EXC_HCC","EXTRACRANIAL_CANCER_DON","FINAL_ALBUMIN","FINAL_ASCITES","FINAL_BILIRUBIN",
"FINAL_CTP_SCORE","FINAL_DIALYSIS_PRIOR_WEEK","FINAL_ENCEPH","FINAL_INR","FINAL_MELD_OR_PELD",
"FINAL_MELD_PELD_LAB_SCORE","FINAL_SERUM_CREAT","FINAL_SERUM_SODIUM","FREE_DON",
"FUNC_STAT_TCR","FUNC_STAT_TRF","FUNC_STAT_TRR","GENDER","GENDER_DON","GRF_FAIL_DATE",
"GRF_STAT","GSTATUS","GTIME","HASHBVVACCINATION","HBEAB_OLD","HBSAB_DON","HBV_CORE",
"HBV_CORE_DON","HBV_DNA_DON","HBV_NAT","HBV_NAT_DON","HBV_SUR_ANTIGEN","HBV_SUR_ANTIGEN_DON",
"HBV_SURF_TOTAL","HBV_TEST_DON","HCC_DIAG","HCC_DIAGNOSIS_TCR","HCC_EVER_APPR",
"HCV_ANTIBODY_DON","HCV_NAT","HCV_NAT_DON","HCV_RIBA_DON","HCV_RNA_DON","HCV_SEROSTATUS",
"HCV_TEST_DON","HEMATOCRIT_DON","HEP_C_ANTI_DON","HEP_DENOVO","HEP_RECUR","HEPARIN_DON",
"HEPATIC_ART_THROM","HEPATIC_OUT_OBS","HEPD_OLD","HGT_CM_CALC","HGT_CM_DON_CALC",
"HGT_CM_TCR","HIST_ALCOHOL_OLD_DON","HIST_CANCER_DON","HIST_CIG_DON","HIST_COCAINE_DON",
"HIST_DIABETES_DON","HIST_HYPERTENS_DON","HIST_INSULIN_DEP_DON","HIST_IV_DRUG_OLD_DON",
"HIST_OTH_DRUG_DON","HISTORY_MI_DON","HIV_NAT","HIV_NAT_DON","HIV_SEROSTATUS","HLAMIS",
"HMO_PPO_DON","HOME_STATE_DON","HTLV1_OLD_DON","HTLV2_OLD_DON","HYPERTENS_DUR_DON","IABP",
"INACT_REASON_CD","INFECT","INIT_AGE","INIT_ALBUMIN","INIT_ASCITES","INIT_BILIRUBIN",
"INIT_BMI_CALC","INIT_CTP_SCORE","INIT_DATE","INIT_DIALYSIS_PRIOR_WEEK","INIT_ENCEPH",
"INIT_HGT_CM","INIT_INR","INIT_MELD_OR_PELD","INIT_MELD_PELD_LAB_SCORE","INIT_OPO_CTR_CODE",
"INIT_SERUM_CREAT","INIT_SERUM_SODIUM","INIT_STAT","INIT_WGT_KG","INO_PROCURE_AGENT_1",
"INO_PROCURE_AGENT_2","INO_PROCURE_AGENT_3","INOTROP_SUPPORT_DON","INOTROPES","INR_TX",
"INSULIN_DEP_DON","INSULIN_DON","INTRACRANIAL_CANCER_DON","LI_ALLOC_STAT","LI_BIOPSY",
"LIFE_SUP_TCR","LIFE_SUP_TRR","LIST_MELD","LISTING_CTR_CODE","LISTYR","LITYP","LIV_DON_TY",
"LIVERCHECKINDATE","LIVERCHECKINTIME","LIVERCHECKINTIMEZONEID","LOS","LT_ONE_WEEK_DON",
"LV_EJECT_DON","LV_EJECT_METH_DON","MACRO_FAT_LI_DON","MALIG","MALIG_TCR","MALIG_TRR",
"MALIG_TY_TRR","MALIG_TYPE","MED_COND_TRR","MEDICAID_DON","MEDICARE_DON",
"MEETSTANDARDCRITERIA","MELD_DIFF_REASON_CD","MELD_PELD_LAB_SCORE","MELDSEXID",
"MICRO_FAT_LI_DON","MMAT_ON_MATCH","MPAT_ON_MATCH","MPEXCEPTFORMID","MRCREATG_OLD",
"MULTIORG","MUSCLE_WAST_TCR","NEOADJUVANT_THERAPY_TCR","NON_HRT_DON","NUM_PREV_TX",
"ON_VENT_TRR","OPO_CTR_CODE","OTH_GOVT_DON","OTH_LIFE_SUP_TCR","OTH_LIFE_SUP_TRR",
"OTHER_HYPERTENS_MED_DON","OTHER_INF_CONF_DON","OTHER_INF_DON","OTHER_VASC_THROMB",
"PERM_STATE","PERM_STATE_TRR","PGE","PH_DON","PORTAL_VEIN_TCR","PORTAL_VEIN_THROM",
"PORTAL_VEIN_TRR","PRETREAT_MED_DON_OLD","PREV_AB_SURG_TCR","PREV_AB_SURG_TRR","PREV_MALIG_TY",
"PREV_PI_TX_TCR_ARCHIVE","PREV_TX","PREV_TX_ANY","PREV_TX_ANY_N","PREV_TX_DATE",
"PRI_GRF_FAIL","PRI_NON_FUNC","PRI_PAYMENT_CTRY_DON","PRI_PAYMENT_CTRY_TCR",
"PRI_PAYMENT_CTRY_TRR","PRI_PAYMENT_DON","PRI_PAYMENT_TCR","PRI_PAYMENT_TRR","PRIV_INS_DON",
"PROTEIN_URINE","PRVTXDIF","PSTATUS","PT_CODE","PT_DIURETICS_DON","PT_OTH_DON",
"PT_STEROIDS_DON","PT_T3_DON","PT_T4_DON","PTIME","PULM_INF_CONF_DON","PULM_INF_DON",
"PX_NON_COMPL","PX_STAT","PX_STAT_DATE","RA1","RA2","RB1","RB2","RDR1","RDR2",
"REASONNOHBVVACCINATIONID","RECOV_COUNTRY","RECOV_OUT_US","RECOVERY_DATE_DON",
"RECUR_DISEASE","REFERRAL_DATE","REGION","REJ_ACUTE","REJ_CHRONIC","REM_CD","RESUSCIT_DUR",
"RETXDATE","SCOREADJUSTMENT","SELF_DON","SGOT_DON","SGPT_DON","SHARE_TY","SKIN_CANCER_DON",
"STATUS_DDR","STATUS_LDR","STATUS_TCR","STATUS_TRR","TATTOOS","TBILI_DON","TBILI_TX",
"TIPSS_TCR","TIPSS_TRR","TOT_SERUM_ALBUM","TRANSFUS_INTRAOP_NUM_OLD_DON",
"TRANSFUS_PRIOR_NUM_OLD_DON","TRANSFUS_TERM_DON","TRANSPLANT_TIME","TRANSPLANTTIMEZONEID",
"TRR_ID_CODE","TRTREJ1Y","TRTREJ6M","TX_DATE","TX_MELD","TX_PROCEDUR_TY","TX_YEAR","TXHRT",
"TXINT","TXKID","TXLIV","TXLNG","TXPAN","TXVCA","URINE_INF_CONF_DON","URINE_INF_DON",
"VAD_TAH","VAL_DT_DDR","VAL_DT_LDR","VAL_DT_TCR","VAL_DT_TRR","VASC_THROMB","VASODIL_DON",
"VDRL_DON","VENTILATOR_TCR","VESSELS_NUM_STEN_DON","WARM_ISCH_TM_DON","WGT_KG_CALC",
"WGT_KG_DON_CALC","WGT_KG_TCR","WL_ID_CODE","WLHL","WLHR","WLIN","WLKI","WLKP","WLLI",
"WLLU","WLPA","WLPI","WLVC","WORK_INCOME_TCR","WORK_INCOME_TRR","YR_ENTRY_US_TCR"
]

df.columns = official_header_list

In [ ]:
df.columns = official_header_list
df.head()

,ABO,ABO_DON,ABO_MAT,ACADEMIC_LEVEL_TCR,ACADEMIC_LEVEL_TRR,ACADEMIC_PRG_TCR,ACADEMIC_PRG_TRR,ACUTE_REJ_EPI,ADMISSION_DATE,ADMIT_DATE_DON,...,WLKI,WLKP,WLLI,WLLU,WLPA,WLPI,WLVC,WORK_INCOME_TCR,WORK_INCOME_TRR,YR_ENTRY_US_TCR
0,.,0,.,F,B,0,62.0000,160.0000,24.2187,NaN,...,1994,.,.,Y,Y,09362,19282,22537,22537,09362
1,.,1,.,F,A,0,53.0000,163.0000,19.9481,NaN,...,1994,.,.,Y,Y,02666,01054,14353,14353,02666
2,.,0,.,F,O,0,54.0000,165.0000,19.8347,NaN,...,1994,.,.,N,Y,Unknown,Unknown,02821,02821,11129
3,.,0,.,M,B,0,89.0000,180.0000,27.4691,NaN,...,1994,.,.,Y,Y,03503,23002,23002,23002,03503
4,.,0,.,F,O,0,57.0000,163.0000,21.4536,NaN,...,1994,.,.,N,Y,Unknown,Unknown,01054,01054,06107

In [ ]:
df.loc[5][150:175]

FINAL_MELD_PELD_LAB_SCORE             .
FINAL_SERUM_CREAT                     .
FINAL_SERUM_SODIUM                    .
FREE_DON                              1
FUNC_STAT_TCR                         2
FUNC_STAT_TRF                         0
FUNC_STAT_TRR                         2
GENDER                                R
GENDER_DON                            1
GRF_FAIL_DATE                         .
GRF_STAT                     04/02/1995
GSTATUS                             NaN
GTIME                               NaN
HASHBVVACCINATION                   NaN
HBEAB_OLD                             W
HBSAB_DON                           NaN
HBV_CORE                            NaN
HBV_CORE_DON                        NaN
HBV_DNA_DON                           N
HBV_NAT                             997
HBV_NAT_DON                           C
HBV_SUR_ANTIGEN                       C
HBV_SUR_ANTIGEN_DON                   N
HBV_SURF_TOTAL                        .
HBV_TEST_DON                          V
Name: 5, dtype: object

In [ ]:
df.shape

(380260, 416)

In [ ]:
df.isna().sum()[:20]

ABO                        0
ABO_DON                    0
ABO_MAT                    0
ACADEMIC_LEVEL_TCR         0
ACADEMIC_LEVEL_TRR         0
ACADEMIC_PRG_TCR           0
ACADEMIC_PRG_TRR           0
ACUTE_REJ_EPI              0
ADMISSION_DATE             0
ADMIT_DATE_DON        378639
AGE                        0
AGE_DON                 6378
AGE_GROUP                  0
ALBUMIN_TX                 0
ALCOHOL_HEAVY_DON          0
AMIS                       0
ANTIHYPE_DON               0
ARGININE_DON               0
ARTIFICIAL_LI_TCR          0
ARTIFICIAL_LI_TRR      26882
dtype: int64

In [ ]:
df["EXC_CASE"].unique()

array(['U', nan, 'Y', 'N'], dtype=object)